name: Check Android Keystore Credentials

on:
  workflow_dispatch:

jobs:
  check-keystore:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Decode keystore
        run: |
          mkdir -p app
          echo "$KEYSTORE_BASE64" | base64 --decode > app/release.keystore

      - name: Debug - file type & size
        run: |
          file app/release.keystore
          ls -lh app/release.keystore

      - name: Debug - secret lengths
        run: |
          echo "KEYSTORE_BASE64 length: ${#KEYSTORE_BASE64}"
          echo "KEYSTORE_PASSWORD length: ${#KEYSTORE_PASSWORD}"
          echo "KEY_ALIAS length: ${#KEY_ALIAS}"
          echo "KEY_PASSWORD length: ${#KEY_PASSWORD}"

      - name: Verify keystore password
        run: |
          keytool -list \
            -keystore app/release.keystore \
            -storepass "$KEYSTORE_PASSWORD" \
            > /dev/null

      - name: Verify alias password
        run: |
          keytool -list \
            -keystore app/release.keystore \
            -storepass "$KEYSTORE_PASSWORD" \
            -alias "$KEY_ALIAS" \
            -keypass "$KEY_PASSWORD" \
            > /dev/null
