name: Check Android Keystore Credentials

on:
  workflow_dispatch:

jobs:
  check-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Decode keystore
        run: |
          mkdir -p app
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > app/release.keystore

      - name: Verify keystore
        run: |
          keytool -list \
            -keystore app/release.keystore \
            -storepass "$ANDROID_KEYSTORE_PASSWORD" \
            -alias "$ANDROID_KEY_ALIAS" \
            -keypass "$ANDROID_KEY_PASSWORD" > /dev/null
