name: Build & Release Signed APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Rename APK with version (replace dots with dashes)
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          SAFE_VERSION=${VERSION//./-}
          mv app/build/outputs/apk/release/app-release.apk screenlite-web-kiosk-$SAFE_VERSION.apk

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: screenlite-web-kiosk-${{ github.ref_name//./- }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
