name: Build & Release Signed APK

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest
    env:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        run: |
          mkdir -p app
          echo "$KEYSTORE_BASE64" | base64 --decode > app/release.keystore

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        env:
          SIGNING_STORE_FILE: app/release.keystore
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Rename APK with version (replace dots with dashes)
        id: rename_apk
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          SAFE_VERSION=${VERSION//./-}
          mv app/build/outputs/apk/release/app-release.apk screenlite-web-kiosk-$SAFE_VERSION.apk
          echo "apk_name=screenlite-web-kiosk-$SAFE_VERSION.apk" >> $GITHUB_OUTPUT

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ steps.rename_apk.outputs.apk_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README with new APK link
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          SAFE_VERSION=${VERSION//./-}
          APK_NAME="screenlite-web-kiosk-$SAFE_VERSION.apk"
          RELEASE_URL="https://github.com/${GITHUB_REPOSITORY}/releases/download/${GITHUB_REF_NAME}/$APK_NAME"
          
          sed -i "s#https://github.com/${GITHUB_REPOSITORY}/releases/download/.*/screenlite-web-kiosk-.*\.apk#$RELEASE_URL#" README.md
          
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update APK link for $VERSION" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF_NAME}